languageCode = "en"
languageName = "English"
weight = 1
title = "Sunsec"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/sunsec-sun.svg"
  # secondaryLogo = "img/background.svg"
  # description = "My awesome website"
  copyright = "© 2025 Sunsec. All Rights Reserved"

[author]
  name = "Sunsec"
  image = "img/sunsec-sun.png"
  headline = "Potiguar by origin, uniting minds to solve security challenges"
  bio = ""
  links = [
    { instagram = "https://www.instagram.com/sunsecrn/" },
    { github = "https://github.com/sunsecrn" },
  ]

