languageCode = "en"
languageName = "English"
weight = 1
title = "Sunsec"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/sunsec-sun.png"
  # secondaryLogo = "img/background.svg"
  # description = "My awesome website"
  copyright = "© 2024 Sunsec. All Rights Reserved"

[author]
  name = "Sunsec"
  image = "img/sunsec.png"
  headline = "Comunidade de segurança da informação potiguar."
  bio = "Comunidade de segurança da informação potiguar."
  links = [
    { instagram = "https://www.instagram.com/sunsecrn/" },
    { discord = "https://discord.gg/WteNq4CvpP" },
    { github = "https://github.com/sunsecrn" },
    { telegram = "https://t.me/sunsecrn" },
  ]

