languageCode = "pt-br"
languageName = "Portugues"
weight = 1
title = "Sunsec"

[params]
  displayName = "Português"
  isoCode = "pt-br"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/sunsec-sun.png"
  secondaryLogo = "Sunsec"
  # description = "My awesome website"
  copyright = "© 2024 Sunsec. All Rights Reserved"

[author]
  name = "Sunsec"
  image = "img/sunsec-sun.png"
  headline = "Potiguar por origem, unindo mentes resolvendo desafios de segurança"
  bio = ""
  links = [
    { instagram = "https://www.instagram.com/sunsecrn/" },
    { github = "https://github.com/sunsecrn" },
  ]

